name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]


jobs:
  trigger-check:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge prbot request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/prbot"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: 'echo Found /prbot comment'
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  review:
    needs: trigger-check
    if: needs.deploy-check.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: xemberi/ai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: 'gpt-3.5-turbo'
          openai_heavy_model: 'gpt-4'
          openai_model_temperature: '0.05'
          openai_retries: '3'
          bot_icon: '<img src="https://avatars.githubusercontent.com/u/112554362?s=200&v=4" alt="Image description" width="20" height="20">'